// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AV2TestesAutomatizados_AnaeRamon.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Retweet de palavras-chave no twitter")]
    public partial class RetweetDePalavras_ChaveNoTwitterFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            var featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Retweet de palavras-chave no twitter", "\tPara seguir todo o conteudo relevantes sobre testes automatizados\r\n\tComo aluno d" +
                    "e testes automatizados\r\n\tDesejo que todo o tweeter com determinadas palavras sob" +
                    "re o assunto seja retweetado automaticamente ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Quero que minha busca no twitter por palavras especificas seja retweetado")]
        public virtual void QueroQueMinhaBuscaNoTwitterPorPalavrasEspecificasSejaRetweetado()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quero que minha busca no twitter por palavras especificas seja retweetado", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que ja realizei minha busca pelas palavras que quero", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("digito a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o sistema deve mostrar quais tweets foram retweetados", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
            testRunner.And("retweetar tudo automaticamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Falha ao tentar Retweetar o mesmo tweet mais de uma vez")]
        public virtual void FalhaAoTentarRetweetarOMesmoTweetMaisDeUmaVez()
        {
            var scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Falha ao tentar Retweetar o mesmo tweet mais de uma vez", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que esqueci que retweetei uma palavra e chamo novamente o boot para relizar o ret" +
                    "weet de novo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("digito a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o sistema deve exibir uma mensagem de erro na hora de realizar a ação de retweet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
