// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AV2TestesAutomatizados_AnaeRamon.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Retweet de palavras chaves no twiter")]
    public partial class RetweetDePalavrasChavesNoTwiterFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Retweet de palavras chaves no twiter", "Para seguir todo o conteudo relevante sobre testes\r\nComo aluno de testes automati" +
                    "zados\r\nDesejo que todo o tweeter com determinadas palavras sobre o assunto seja " +
                    "retweetado automaticamente ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Quero retweetar as palavras cadastrada no sistema")]
        public virtual void QueroRetweetarAsPalavrasCadastradaNoSistema()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Quero retweetar as palavras cadastrada no sistema", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"Tamagochi\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("quero que o robo retweet tudo sobre a palavra automaticamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar o mesmo tweet")]
        public virtual void RetweetarOMesmoTweet()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar o mesmo tweet", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que tento retweetar novamente sobre a palavra \"Tamagochi\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o sistema deve exibir uma mensagem de erro na hora de realizar a ação de retweet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
