// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace AV2TestesAutomatizados_AnaeRamon.Specs.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Retweet de palavras chaves no twiter")]
    public partial class RetweetDePalavrasChavesNoTwiterFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Retweet de palavras chaves no twiter", "Para seguir todo o conteudo relevante sobre testes\r\nComo aluno de testes automati" +
                    "zados\r\nDesejo que todo o tweeter com determinadas palavras sobre o assunto seja " +
                    "retweetado automaticamente ", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar o mesmo tweet")]
        public virtual void RetweetarOMesmoTweet()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar o mesmo tweet", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que tento retweetar novamente sobre a palavra \"testegruporamoneanateste\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o sistema deve exibir uma mensagem de erro na hora de realizar a ação de retweet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas em maiúsculo")]
        public virtual void RetweetarPalavrasCadastradasEmMaiusculo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas em maiúsculo", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que tento retweetar novamente sobre a palavra \"TESTEGRUPOANAERAMONTESTE\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de iniciar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o sistema deve exibir uma mensagem de erro na hora de realizar a ação de retweet", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas em minúsculo")]
        public virtual void RetweetarPalavrasCadastradasEmMinusculo()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas em minúsculo", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"testegruporamoneanateste\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de inicar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o robo deve retweetar tweets sobre a palavra \"testegruporamoneanateste\" automatic" +
                    "amente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas no singular")]
        public virtual void RetweetarPalavrasCadastradasNoSingular()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas no singular", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"testegruporamoneanateste\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de inicar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o robo deve retweetar tweets sobre a palavra \"testegruporamoneanateste\" automatic" +
                    "amente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas no plural")]
        public virtual void RetweetarPalavrasCadastradasNoPlural()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas no plural", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"testegruporamoneanatestes\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de inicar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o robo deve retweetar tweets sobre a palavra \"testegruporamoneanatestes\" automati" +
                    "camente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas com caracteres especiais")]
        public virtual void RetweetarPalavrasCadastradasComCaracteresEspeciais()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas com caracteres especiais", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"testegruporamoneanatestes!@#$%¨&\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de inicar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o robo deve retweetar tweets sobre a palavra \"testegruporamoneanatestes!@#$%¨&\" a" +
                    "utomaticamente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Retweetar palavras cadastradas com espaço")]
        public virtual void RetweetarPalavrasCadastradasComEspaco()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Retweetar palavras cadastradas com espaço", ((string[])(null)));
            this.ScenarioSetup(scenarioInfo);
            testRunner.Given("que cadastrei a palavra \"testegruporamon eanateste\" no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
            testRunner.When("seleciono a opção de inicar boot", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
            testRunner.Then("o robo deve retweetar tweets sobre a palavra \"testegruporamon eanateste\" automati" +
                    "camente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
